### ISSUE TITLE
가게 정보 공통 컴포넌트 

### ISSUE THREAD

**Issue by y00n1verse** [codeit-frontend-part3-team3/The-julge#46]
## 작업 내용

가게 정보 등록/편집 공통 컴포넌트 구현

---

### 예상 완료 날짜
12-18

---

### 추가 정보

가게 폼이라는 의미에서 컴포넌트명은 StoreForm으로 정했습니다!

**Comment by swp91** [comment]
앗 지윤님 다음부터는 날짜 작성해주실떄 양식에 써논
작업 완료를 목표로 하는 날짜: 12-18 <- 요거 그대로 써주시면 감사할것같습니다
깃허브 액션이 저 텍스트를 추적해서 지라에 기한을 할당하는거라서요 😭😭

**Comment by y00n1verse** [comment]
앗! 몰랐네요.. 죄송합니당..ㅎㅎ
